# -*- coding: utf-8 -*-
"""week3 A108260024  李昊恩.jpynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15S0OXvNdwAQyO7y1A_PDRklRM-3Y8xzN
"""

print("Hello world")

print("I'm 李昊恩")